# Generated by Django 5.2.17 on 2026-08-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_specialty_user_specialties"),
        ("branches", "0001_initial"),
        ("referrals", "0001_initial"),
        ("scheduling", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="source_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="visits.visit",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="target_appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral",
                to="scheduling.appointment",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="to_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals_in",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="to_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="to_specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="accounts.specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["status", "to_branch"], name="referrals_r_status_03f3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["to_doctor", "status"], name="referrals_r_to_doct_d1d927_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["patient"], name="referrals_r_patient_563506_idx"
            ),
        ),
    ]
