# Generated by Django 5.2.17 on 2026-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name_plural": "specialties",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Специальности врача — по ним подбираются кандидаты для направления 'на специальность' (Referral.to_specialty), без выбора конкретного коллеги.",
                related_name="doctors",
                to="accounts.specialty",
            ),
        ),
    ]
