# Generated by Django 5.2.17 on 2026-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_specialty_user_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="license_expires_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Срок действия лицензии"
            ),
        ),
    ]
