# Generated by Django 5.2.17 on 2026-08-31 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_service_invoiceline_service_branchpriceoverride"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="insurance_covered_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Снимок доли счёта, покрытой страховой — считается один раз при issue(), см. докстринг класса.",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=100)),
                (
                    "coverage_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Какую долю каждого счёта покрывает страховая (0-100%).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "coverage_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Общий лимит покрытия по полису — сумма всех счетов, оплаченных страховой, не может его превысить.",
                        max_digits=12,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="finance.insuranceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="insurance_policy",
            field=models.ForeignKey(
                blank=True,
                help_text="Полис, по которому разделяется чек — необязателен (обычная оплата, если не указан).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="finance.insurancepolicy",
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["patient"], name="finance_ins_patient_8df66c_idx"
            ),
        ),
    ]
