# Generated by Django 5.2.17 on 2026-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_insuranceprovider_invoice_insurance_covered_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("card", "Карта"),
                    ("qr", "QR / Мобильный"),
                    ("bonus", "Бонусами"),
                    ("other", "Другое"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
