# Generated by Django 5.2.17 on 2026-08-31 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurnRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_visit_date",
                    models.DateTimeField(
                        help_text="Visit.created_at последнего COMPLETED-визита пациента.",
                        verbose_name="Дата последнего визита",
                    ),
                ),
                (
                    "avg_interval_days",
                    models.FloatField(
                        help_text="Средний интервал между завершёнными визитами пациента.",
                        verbose_name="Средний межвизитный интервал (дней)",
                    ),
                ),
                (
                    "days_overdue",
                    models.PositiveIntegerField(
                        help_text="На сколько дней пациент превысил свой обычный интервал визитов.",
                        verbose_name="Просрочено дней",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        help_text="days_overdue / avg_interval_days — простая формула, не ML-модель. 1.0 = просрочен ровно на один свой обычный интервал, выше — больше.",
                        verbose_name="Оценка риска",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("acknowledged", "Принято в работу"),
                            ("reactivated", "Пациент вернулся"),
                            ("dismissed", "Отклонено"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="churn_risks",
                        to="branches.branch",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="churn_risks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score"],
                "indexes": [
                    models.Index(
                        fields=["branch", "status"],
                        name="churn_churn_branch__a53122_idx",
                    ),
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="churn_churn_patient_c574dd_idx",
                    ),
                ],
            },
        ),
    ]
