# Generated by Django 5.2.17 on 2026-08-31 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("patients", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(max_length=200, verbose_name="Тип анализа"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Плановое"),
                            ("urgent", "Срочное"),
                            ("emergency", "Экстренное"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Заказан"),
                            ("completed", "Есть результат"),
                            ("cancelled", "Отменён"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="branches.branch",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "source_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Осмотр, из карты которого заказан анализ — необязателен (можно заказать и вне текущего приёма).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_text", models.TextField(verbose_name="Результат")),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False, verbose_name="Результат вне нормы"
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="diagnostics.laborder",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient", "-created_at"], name="diagnostics_patient_ab2694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["branch", "status"], name="diagnostics_branch__24ef2b_idx"
            ),
        ),
    ]
