# Generated by Django 5.2.17 on 2026-08-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_specialty_user_specialties"),
        ("branches", "0001_initial"),
        ("patients", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriageSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram")],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                (
                    "external_chat_id",
                    models.CharField(
                        help_text="Например, Telegram chat_id — куда отправить ответ пациенту.",
                        max_length=64,
                        verbose_name="ID чата в канале",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Имя из чата"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Телефон из чата"
                    ),
                ),
                (
                    "symptom_text",
                    models.TextField(
                        verbose_name="Жалоба пациента (как есть, из чата)"
                    ),
                ),
                ("suggested_starts_at", models.DateTimeField()),
                ("suggested_ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("expired", "Слот больше не актуален"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triage_suggestions",
                        to="branches.branch",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triage_suggestions",
                        to="accounts.specialty",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triage_suggestions",
                        to="patients.patient",
                    ),
                ),
                (
                    "resulting_appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_suggestion",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "suggested_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triage_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "status"],
                        name="triage_tria_branch__71acf7_idx",
                    ),
                    models.Index(
                        fields=["channel", "external_chat_id"],
                        name="triage_tria_channel_6fcb3a_idx",
                    ),
                ],
            },
        ),
    ]
