# Generated by Django 5.2.17 on 2026-09-02 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triagesuggestion",
            name="match_confidence",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Уверенность классификатора (%)",
            ),
        ),
    ]
