# Generated by Django 5.2.17 on 2026-08-31 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Номер койки внутри палаты, напр. «1».", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Свободна"),
                            ("occupied", "Занята"),
                            ("cleaning", "Уборка"),
                            ("reserved", "Резерв"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["room_id", "label"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.SlugField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis_at_admission",
                    models.TextField(verbose_name="Диагноз при поступлении"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("discharged", "Выписан")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "admitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discharge_epicrisis",
                    models.TextField(blank=True, verbose_name="Выписной эпикриз"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions_attending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="patients.patient",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="inpatient.bed",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="inpatient.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-admitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Номер/название палаты, напр. «204».", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="inpatient.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beds",
                to="inpatient.room",
            ),
        ),
        migrations.CreateModel(
            name="StaffDepartmentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="inpatient.department",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_department_code_per_branch"
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["department", "status"], name="inpatient_a_departm_a7187b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["patient", "-admitted_at"],
                name="inpatient_a_patient_0aa045_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["bed", "status"], name="inpatient_a_bed_id_fb09b2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("department", "name"), name="unique_room_name_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                fields=("room", "label"), name="unique_bed_label_per_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffdepartmentassignment",
            constraint=models.UniqueConstraint(
                fields=("staff", "department"), name="unique_staff_department"
            ),
        ),
    ]
