# Generated by Django 5.2.17 on 2026-08-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0002_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("medication", "Медикамент"),
                            ("procedure", "Процедура"),
                            ("diet", "Диета"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Назначение"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда должно быть выполнено — необязательно.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Назначено"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("performed_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_orders_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admission", "status"],
                        name="inpatient_c_admissi_1bb93c_idx",
                    )
                ],
            },
        ),
    ]
