# Generated by Django 5.2.17 on 2026-08-31 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0003_clinicalorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="АД систолическое"
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="АД диастолическое"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Пульс"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Температура",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vitals_records",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vitals_records_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["admission", "-recorded_at"],
                        name="inpatient_v_admissi_580319_idx",
                    )
                ],
            },
        ),
    ]
