# Generated by Django 5.2.17 on 2026-08-31 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inpatient", "0004_vitalsrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_rooms",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_name",
                    models.CharField(max_length=255, verbose_name="Операция"),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирована"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("sign_in_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("time_out_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("sign_out_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "lead_surgeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="inpatient.operatingroom",
                    ),
                ),
                (
                    "sign_in_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sign_out_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Остальной состав операционной бригады.",
                        related_name="operations_assisted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_out_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="operatingroom",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="unique_operating_room_name_per_branch"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["operating_room", "starts_at"],
                name="inpatient_o_operati_376daf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["admission", "status"], name="inpatient_o_admissi_6c953f_idx"
            ),
        ),
    ]
