# Generated by Django 5.2.17 on 2026-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0005_operatingroom_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Аллергии, план на ближайшую операцию и т.п. — отдельно от клинического диагноза.",
                verbose_name="Заметки при поступлении",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="reason",
            field=models.CharField(
                choices=[
                    ("planned", "Плановая операция"),
                    ("emergency", "Экстренная госпитализация"),
                    ("transfer", "Перевод из другого отделения"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Основание госпитализации",
            ),
        ),
    ]
