# Generated by Django 5.2.17 on 2026-09-02 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0006_admission_notes_admission_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsrecord",
            name="spo2",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Сатурация (SpO₂), %",
            ),
        ),
    ]
