# Generated by Django 5.2.17 on 2026-08-31 16:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100, unique=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="Единица учёта, например: шт, мл, уп.", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Порог алерта «остаток ниже минимума» — 0 значит алерт не нужен.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="branches.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branch_stocks",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch"], name="inventory_s_branch__82793e_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "branch"),
                        name="one_stock_row_per_product_branch",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("restock", "Поступление"),
                            ("consumption", "Списание"),
                            ("adjustment", "Корректировка"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
                (
                    "source_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приём, при закрытии которого произошло списание — необязателен.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "branch", "-created_at"],
                        name="inventory_s_product_46c4ea_idx",
                    ),
                    models.Index(
                        fields=["branch", "-created_at"],
                        name="inventory_s_branch__50a903_idx",
                    ),
                ],
            },
        ),
    ]
