# Generated by Django 5.2.17 on 2026-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="loyalty_points",
            field=models.IntegerField(default=0, verbose_name="Бонусные баллы"),
        ),
    ]
