# Generated by Django 5.2.17 on 2026-08-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("patients", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Повод обращения"
                    ),
                ),
                (
                    "clinical_note",
                    models.TextField(blank=True, verbose_name="Клиническая заметка"),
                ),
                (
                    "diagnosis_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Свободная структура — в проекте пока нет отдельной модели одонтограммы/диагноза, которую можно было бы снимать; формируется позже, когда появится.",
                        verbose_name="Диагноз (снимок)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Идёт приём"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Календарная запись, из которой возник приём. Пусто — визит без предварительной записи (walk-in).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="branches.branch",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="visits_visi_patient_900dd2_idx",
                    ),
                    models.Index(
                        fields=["branch", "doctor"],
                        name="visits_visi_branch__1545aa_idx",
                    ),
                ],
            },
        ),
    ]
